-- =============================================================================
-- LOCAL VALIDATION ONLY — NOT A MIGRATION
-- =============================================================================
--
-- Purpose:
--   Stub the minimum legacy public objects missing from Git so the existing
--   202510* repository migrations can apply on a fresh local Supabase database.
--
-- Scope:
--   - Local developer validation (WP-02B harness)
--   - Must be applied manually BEFORE chronological repository migrations
--   - Must NOT be deployed remotely or added to supabase_migrations history
--
-- Idempotent:
--   Safe to re-run on an empty or partially-initialized local instance.
--
-- Note:
--   A deadline may not be newly declared in the past in webproc, but legacy
--   public tables here are quarantined reference stubs only.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- public.t_processoweb (parent of arquivos_enviados FK)
-- Columns aligned with src/integrations/supabase/types.ts (minimal/nullable)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t_processoweb (
  id_proc integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid,
  cod_cli integer,
  dt_entrada timestamptz,
  dt_fatal timestamptz,
  instrucao text,
  n_processo text,
  nome_cli text,
  obs text,
  reclamado text,
  reclamante text,
  status text
);

-- ---------------------------------------------------------------------------
-- public.t_docsprocessos (policy-drop target in 20251002135826)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t_docsprocessos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proc integer,
  link_doc text,
  nome_doc text
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 't_docsprocessos_id_proc_fkey'
  ) THEN
    ALTER TABLE public.t_docsprocessos
      ADD CONSTRAINT t_docsprocessos_id_proc_fkey
      FOREIGN KEY (id_proc)
      REFERENCES public.t_processoweb (id_proc);
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- RLS enabled (20251002135826 operates on policies for these tables)
-- ---------------------------------------------------------------------------

ALTER TABLE public.t_processoweb ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.t_docsprocessos ENABLE ROW LEVEL SECURITY;

-- Placeholder policies with exact names dropped by 20251002135826.
-- Not strictly required (DROP POLICY IF EXISTS tolerates missing policies),
-- but included so local behavior mirrors the historical patch context.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 't_processoweb'
      AND policyname = 'Leitura pública'
  ) THEN
    CREATE POLICY "Leitura pública"
      ON public.t_processoweb
      FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 't_docsprocessos'
      AND policyname = 'Leitura pública'
  ) THEN
    CREATE POLICY "Leitura pública"
      ON public.t_docsprocessos
      FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 't_processoweb'
      AND policyname = 'Cliente vê seus processos'
  ) THEN
    CREATE POLICY "Cliente vê seus processos"
      ON public.t_processoweb
      FOR SELECT
      TO authenticated
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 't_docsprocessos'
      AND policyname = 'Cliente vê seus documentos'
  ) THEN
    CREATE POLICY "Cliente vê seus documentos"
      ON public.t_docsprocessos
      FOR SELECT
      TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.t_processoweb p
          WHERE p.id_proc = t_docsprocessos.id_proc
            AND p.user_id = auth.uid()
        )
      );
  END IF;
END;
$$;

-- Grants for local Supabase roles (legacy quarantine; not webproc runtime)
GRANT SELECT, INSERT, UPDATE, DELETE ON public.t_processoweb TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.t_docsprocessos TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;
