-- WP-03 Step 2B-Foundation: Actus internal read access (database only)
-- Depends on: 20260307280000_wp03_documentos_domain.sql
--
-- Actus visibility across EM_PREENCHIMENTO is technical read access only.
-- Operational release remains the existing EM_PREENCHIMENTO -> PENDENTE transition.

-- ---------------------------------------------------------------------------
-- webproc.usuarios_actus
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.usuarios_actus (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  nome text,
  email text NOT NULL,
  papel text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuarios_actus_papel_check CHECK (papel IN ('ADMIN', 'OPERADOR'))
);

CREATE UNIQUE INDEX usuarios_actus_user_id_unique
  ON webproc.usuarios_actus (user_id);

CREATE UNIQUE INDEX usuarios_actus_email_unique
  ON webproc.usuarios_actus (lower(email));

CREATE INDEX usuarios_actus_ativo_idx
  ON webproc.usuarios_actus (ativo)
  WHERE ativo = true;

CREATE TRIGGER usuarios_actus_set_updated_at
  BEFORE UPDATE ON webproc.usuarios_actus
  FOR EACH ROW
  EXECUTE FUNCTION webproc.set_updated_at();

COMMENT ON TABLE webproc.usuarios_actus IS
  'Registered human Actus operators/admins. Runtime authorization uses user_id/auth.uid(), not email. ADMIN and OPERADOR share the same WebProc operational read scope in v1.';

COMMENT ON COLUMN webproc.usuarios_actus.papel IS
  'v1 roles ADMIN and OPERADOR share identical WebProc domain read authority. Role distinction is reserved for future internal administration only.';

-- ---------------------------------------------------------------------------
-- Private authorization helper
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION webproc_private.is_active_actus_user()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = webproc, webproc_private, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM webproc.usuarios_actus ua
    WHERE ua.user_id = auth.uid()
      AND ua.ativo = true
  );
$$;

REVOKE ALL ON FUNCTION webproc_private.is_active_actus_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION webproc_private.is_active_actus_user() TO authenticated;

COMMENT ON FUNCTION webproc_private.is_active_actus_user() IS
  'Returns true when auth.uid() is an active Actus user. SECURITY DEFINER helper for RLS only; does not grant mutation authority.';

-- ---------------------------------------------------------------------------
-- usuarios_actus security (no authenticated Data API access)
-- ---------------------------------------------------------------------------

REVOKE ALL ON TABLE webproc.usuarios_actus FROM PUBLIC;
REVOKE ALL ON TABLE webproc.usuarios_actus FROM authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON webproc.usuarios_actus TO service_role;

ALTER TABLE webproc.usuarios_actus ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Extend SELECT authorization (read-only; no mutation broadening)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "clientes_select_member" ON webproc.clientes;

CREATE POLICY "clientes_select_member"
  ON webproc.clientes
  FOR SELECT
  TO authenticated
  USING (
    webproc_private.is_active_actus_user()
    OR (
      ativo = true
      AND EXISTS (
        SELECT 1
        FROM webproc.usuarios_clientes uc
        WHERE uc.cliente_id = clientes.id
          AND uc.user_id = auth.uid()
          AND uc.ativo = true
      )
    )
  );

DROP POLICY IF EXISTS "processos_select_same_client" ON webproc.processos;

CREATE POLICY "processos_select_same_client"
  ON webproc.processos
  FOR SELECT
  TO authenticated
  USING (
    webproc_private.is_active_actus_user()
    OR EXISTS (
      SELECT 1
      FROM webproc.usuarios_clientes uc
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
        AND uc.cliente_id = processos.cliente_id
    )
  );

DROP POLICY IF EXISTS "processo_documentos_select_same_client" ON webproc.processo_documentos;

CREATE POLICY "processo_documentos_select_same_client"
  ON webproc.processo_documentos
  FOR SELECT
  TO authenticated
  USING (
    webproc_private.is_active_actus_user()
    OR EXISTS (
      SELECT 1
      FROM webproc.processos p
      INNER JOIN webproc.usuarios_clientes uc ON uc.cliente_id = p.cliente_id
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE p.id_proc = processo_documentos.id_proc
        AND uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
    )
  );
