-- WP-01: Greenfield WebProc schema (does not modify legacy public objects)

CREATE SCHEMA IF NOT EXISTS webproc;

GRANT USAGE ON SCHEMA webproc TO authenticated;

-- ---------------------------------------------------------------------------
-- updated_at trigger (webproc schema only)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION webproc.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- A1. webproc.clientes
-- TD-WP-01: temporary client master until FlowProc integration
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.clientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_cliente bigint NOT NULL,
  nome text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clientes_codigo_cliente_unique UNIQUE (codigo_cliente)
);

CREATE TRIGGER clientes_set_updated_at
  BEFORE UPDATE ON webproc.clientes
  FOR EACH ROW
  EXECUTE FUNCTION webproc.set_updated_at();

-- ---------------------------------------------------------------------------
-- A2. webproc.usuarios_clientes
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.usuarios_clientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id bigint NOT NULL REFERENCES webproc.clientes (id),
  user_id uuid REFERENCES auth.users (id),
  email text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX usuarios_clientes_cliente_email_unique
  ON webproc.usuarios_clientes (cliente_id, lower(email));

CREATE UNIQUE INDEX usuarios_clientes_cliente_user_unique
  ON webproc.usuarios_clientes (cliente_id, user_id)
  WHERE user_id IS NOT NULL;

CREATE TRIGGER usuarios_clientes_set_updated_at
  BEFORE UPDATE ON webproc.usuarios_clientes
  FOR EACH ROW
  EXECUTE FUNCTION webproc.set_updated_at();

-- ---------------------------------------------------------------------------
-- A3. webproc.processos
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.processos (
  id_proc bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id bigint NOT NULL REFERENCES webproc.clientes (id),
  created_by uuid NOT NULL REFERENCES auth.users (id),
  n_processo text,
  exec_prov text,
  nome_cli text,
  reclamante text,
  reclamado text,
  instituicao text,
  instrucao text,
  obs text,
  dt_entrada timestamptz NOT NULL DEFAULT now(),
  dt_fatal timestamptz,
  status text NOT NULL DEFAULT 'EM_PREENCHIMENTO',
  pendente_at timestamptz,
  importado_at timestamptz,
  concluido_at timestamptz,
  cancelado_at timestamptz,
  cancelado_por uuid REFERENCES auth.users (id),
  motivo_cancelamento text,
  origem_cancelamento text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT processos_status_check CHECK (
    status IN (
      'EM_PREENCHIMENTO',
      'PENDENTE',
      'IMPORTADO',
      'CONCLUIDO',
      'CANCELADO'
    )
  )
);

CREATE TRIGGER processos_set_updated_at
  BEFORE UPDATE ON webproc.processos
  FOR EACH ROW
  EXECUTE FUNCTION webproc.set_updated_at();

-- ---------------------------------------------------------------------------
-- A4. webproc.processo_documentos
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.processo_documentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_proc bigint NOT NULL REFERENCES webproc.processos (id_proc) ON DELETE CASCADE,
  tipo text NOT NULL,
  nome text,
  url text,
  object_key text,
  nome_arquivo text,
  content_type text,
  tamanho bigint,
  created_by uuid NOT NULL REFERENCES auth.users (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT processo_documentos_tipo_check CHECK (tipo IN ('LINK', 'ARQUIVO')),
  CONSTRAINT processo_documentos_link_arquivo_check CHECK (
    (tipo = 'LINK' AND url IS NOT NULL AND object_key IS NULL)
    OR (tipo = 'ARQUIVO' AND object_key IS NOT NULL AND url IS NULL)
  )
);

-- ---------------------------------------------------------------------------
-- Grants for authenticated role
-- ---------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE ON webproc.clientes TO authenticated;
GRANT SELECT ON webproc.usuarios_clientes TO authenticated;
GRANT SELECT, INSERT, UPDATE ON webproc.processos TO authenticated;
GRANT SELECT ON webproc.processo_documentos TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA webproc TO authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE webproc.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE webproc.usuarios_clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE webproc.processos ENABLE ROW LEVEL SECURITY;
ALTER TABLE webproc.processo_documentos ENABLE ROW LEVEL SECURITY;

-- usuarios_clientes: read own active membership
CREATE POLICY "membership_select_own"
  ON webproc.usuarios_clientes
  FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid()
    AND ativo = true
  );

-- clientes: read active client linked to membership
CREATE POLICY "clientes_select_member"
  ON webproc.clientes
  FOR SELECT
  TO authenticated
  USING (
    ativo = true
    AND EXISTS (
      SELECT 1
      FROM webproc.usuarios_clientes uc
      WHERE uc.cliente_id = clientes.id
        AND uc.user_id = auth.uid()
        AND uc.ativo = true
    )
  );

-- processos: same-client read
CREATE POLICY "processos_select_same_client"
  ON webproc.processos
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM webproc.usuarios_clientes uc
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
        AND uc.cliente_id = processos.cliente_id
    )
  );

-- processos: insert for active client, creator = auth.uid()
CREATE POLICY "processos_insert_member"
  ON webproc.processos
  FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM webproc.usuarios_clientes uc
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
        AND uc.cliente_id = processos.cliente_id
    )
  );

-- processos: update only own created records within active client
CREATE POLICY "processos_update_creator"
  ON webproc.processos
  FOR UPDATE
  TO authenticated
  USING (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM webproc.usuarios_clientes uc
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
        AND uc.cliente_id = processos.cliente_id
    )
  )
  WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM webproc.usuarios_clientes uc
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
        AND uc.cliente_id = processos.cliente_id
    )
  );

-- processo_documentos: same-client read via process
CREATE POLICY "processo_documentos_select_same_client"
  ON webproc.processo_documentos
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM webproc.processos p
      INNER JOIN webproc.usuarios_clientes uc ON uc.cliente_id = p.cliente_id
      INNER JOIN webproc.clientes c ON c.id = uc.cliente_id
      WHERE p.id_proc = processo_documentos.id_proc
        AND uc.user_id = auth.uid()
        AND uc.ativo = true
        AND c.ativo = true
    )
  );
