-- WP-02B.1: operational evidence schema (events, situations, material changes, interventions)

-- ---------------------------------------------------------------------------
-- webproc.operacional_eventos
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.operacional_eventos (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proc bigint NOT NULL REFERENCES webproc.processos (id_proc),
  cliente_id bigint NOT NULL REFERENCES webproc.clientes (id),
  event_type text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor_user_id uuid REFERENCES auth.users (id),
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT operacional_eventos_event_type_check CHECK (
    event_type IN (
      'PROCESS_CREATED',
      'DEADLINE_CHANGED',
      'PROTOCOLIZED',
      'REOPENED'
    )
  ),
  CONSTRAINT operacional_eventos_event_data_object CHECK (jsonb_typeof(event_data) = 'object')
);

CREATE INDEX operacional_eventos_id_proc_occurred_idx
  ON webproc.operacional_eventos (id_proc, occurred_at DESC);

CREATE INDEX operacional_eventos_cliente_occurred_idx
  ON webproc.operacional_eventos (cliente_id, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- webproc.operacional_situacoes
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.operacional_situacoes (
  situation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_proc bigint NOT NULL REFERENCES webproc.processos (id_proc),
  cliente_id bigint NOT NULL REFERENCES webproc.clientes (id),
  situation_type text NOT NULL,
  lifecycle_state text NOT NULL,
  temporal_state text,
  detected_at timestamptz NOT NULL DEFAULT now(),
  last_evaluated_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolution_reason text,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT operacional_situacoes_situation_type_check CHECK (
    situation_type IN (
      'DEADLINE_APPROACHING_NOT_RELEASED',
      'DEADLINE_EXPIRED_NOT_RELEASED'
    )
  ),
  CONSTRAINT operacional_situacoes_lifecycle_state_check CHECK (
    lifecycle_state IN ('ACTIVE', 'RESOLVED')
  ),
  CONSTRAINT operacional_situacoes_temporal_state_check CHECK (
    temporal_state IS NULL
    OR temporal_state IN ('D+1', 'D0', 'EXPIRED')
  ),
  CONSTRAINT operacional_situacoes_resolution_check CHECK (
    (lifecycle_state = 'ACTIVE' AND resolved_at IS NULL AND resolution_reason IS NULL)
    OR (
      lifecycle_state = 'RESOLVED'
      AND resolved_at IS NOT NULL
      AND resolution_reason IS NOT NULL
    )
  ),
  CONSTRAINT operacional_situacoes_resolution_reason_check CHECK (
    resolution_reason IS NULL
    OR resolution_reason IN ('PROTOCOLIZED', 'DEADLINE_CHANGED', 'DEADLINE_EXPIRED')
  )
);

CREATE UNIQUE INDEX operacional_situacoes_one_active_per_type_uq
  ON webproc.operacional_situacoes (id_proc, situation_type)
  WHERE lifecycle_state = 'ACTIVE';

CREATE INDEX operacional_situacoes_id_proc_detected_idx
  ON webproc.operacional_situacoes (id_proc, detected_at DESC);

CREATE INDEX operacional_situacoes_active_lookup_idx
  ON webproc.operacional_situacoes (id_proc, situation_type, lifecycle_state)
  WHERE lifecycle_state = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- webproc.operacional_situacao_mudancas
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.operacional_situacao_mudancas (
  change_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  situation_id uuid NOT NULL REFERENCES webproc.operacional_situacoes (situation_id),
  id_proc bigint NOT NULL REFERENCES webproc.processos (id_proc),
  cliente_id bigint NOT NULL REFERENCES webproc.clientes (id),
  change_type text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  previous_value text,
  new_value text,
  change_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT operacional_situacao_mudancas_change_type_check CHECK (
    change_type IN (
      'SITUATION_CREATED',
      'TEMPORAL_STATE_CHANGED',
      'SITUATION_RESOLVED'
    )
  )
);

CREATE INDEX operacional_situacao_mudancas_situation_idx
  ON webproc.operacional_situacao_mudancas (situation_id, occurred_at ASC);

CREATE INDEX operacional_situacao_mudancas_id_proc_occurred_idx
  ON webproc.operacional_situacao_mudancas (id_proc, occurred_at ASC);

-- ---------------------------------------------------------------------------
-- webproc.operacional_intervencoes
-- ---------------------------------------------------------------------------

CREATE TABLE webproc.operacional_intervencoes (
  intervention_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  situation_id uuid NOT NULL REFERENCES webproc.operacional_situacoes (situation_id),
  id_proc bigint NOT NULL REFERENCES webproc.processos (id_proc),
  cliente_id bigint NOT NULL REFERENCES webproc.clientes (id),
  intervention_type text NOT NULL,
  channel text NOT NULL,
  available_at timestamptz NOT NULL DEFAULT now(),
  first_presented_at timestamptz,
  last_presented_at timestamptz,
  presentation_count integer NOT NULL DEFAULT 0,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT operacional_intervencoes_type_check CHECK (
    intervention_type IN ('DEADLINE_ALERT')
  ),
  CONSTRAINT operacional_intervencoes_channel_check CHECK (
    channel IN ('WEBPROC')
  ),
  CONSTRAINT operacional_intervencoes_presentation_count_check CHECK (
    presentation_count >= 0
  )
);

CREATE UNIQUE INDEX operacional_intervencoes_one_per_situation_uq
  ON webproc.operacional_intervencoes (situation_id, intervention_type, channel);

CREATE INDEX operacional_intervencoes_id_proc_available_idx
  ON webproc.operacional_intervencoes (id_proc, available_at DESC);

-- Worker candidate support index on processos
CREATE INDEX processos_temporal_worker_candidates_idx
  ON webproc.processos (((dt_fatal AT TIME ZONE 'America/Sao_Paulo')::date))
  WHERE status = 'EM_PREENCHIMENTO'
    AND dt_fatal IS NOT NULL;

-- ---------------------------------------------------------------------------
-- cliente_id integrity (denormalized operational evidence)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION webproc_private.enforce_operacional_cliente_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = webproc, webproc_private, pg_temp
AS $$
DECLARE
  v_cliente_id bigint;
BEGIN
  SELECT p.cliente_id
  INTO v_cliente_id
  FROM webproc.processos p
  WHERE p.id_proc = NEW.id_proc;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'processo_not_found'
      USING ERRCODE = 'P0001';
  END IF;

  IF NEW.cliente_id IS DISTINCT FROM v_cliente_id THEN
    RAISE EXCEPTION 'operacional_cliente_id_mismatch'
      USING ERRCODE = 'P0001';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER operacional_eventos_enforce_cliente_id
  BEFORE INSERT ON webproc.operacional_eventos
  FOR EACH ROW
  EXECUTE FUNCTION webproc_private.enforce_operacional_cliente_id();

CREATE TRIGGER operacional_situacoes_enforce_cliente_id
  BEFORE INSERT ON webproc.operacional_situacoes
  FOR EACH ROW
  EXECUTE FUNCTION webproc_private.enforce_operacional_cliente_id();

CREATE TRIGGER operacional_situacao_mudancas_enforce_cliente_id
  BEFORE INSERT ON webproc.operacional_situacao_mudancas
  FOR EACH ROW
  EXECUTE FUNCTION webproc_private.enforce_operacional_cliente_id();

CREATE TRIGGER operacional_intervencoes_enforce_cliente_id
  BEFORE INSERT ON webproc.operacional_intervencoes
  FOR EACH ROW
  EXECUTE FUNCTION webproc_private.enforce_operacional_cliente_id();

-- ---------------------------------------------------------------------------
-- Grants and RLS
-- ---------------------------------------------------------------------------

REVOKE ALL ON TABLE webproc.operacional_eventos FROM PUBLIC;
REVOKE ALL ON TABLE webproc.operacional_situacoes FROM PUBLIC;
REVOKE ALL ON TABLE webproc.operacional_situacao_mudancas FROM PUBLIC;
REVOKE ALL ON TABLE webproc.operacional_intervencoes FROM PUBLIC;

REVOKE INSERT, UPDATE, DELETE ON TABLE webproc.operacional_eventos FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE webproc.operacional_situacoes FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE webproc.operacional_situacao_mudancas FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE webproc.operacional_intervencoes FROM authenticated;

GRANT SELECT ON TABLE webproc.operacional_eventos TO authenticated;
GRANT SELECT ON TABLE webproc.operacional_situacoes TO authenticated;
GRANT SELECT ON TABLE webproc.operacional_situacao_mudancas TO authenticated;
GRANT SELECT ON TABLE webproc.operacional_intervencoes TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA webproc TO authenticated;

ALTER TABLE webproc.operacional_eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE webproc.operacional_situacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE webproc.operacional_situacao_mudancas ENABLE ROW LEVEL SECURITY;
ALTER TABLE webproc.operacional_intervencoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "operacional_eventos_select_same_client"
  ON webproc.operacional_eventos
  FOR SELECT
  TO authenticated
  USING (webproc_private.has_active_client_membership(cliente_id));

CREATE POLICY "operacional_situacoes_select_same_client"
  ON webproc.operacional_situacoes
  FOR SELECT
  TO authenticated
  USING (webproc_private.has_active_client_membership(cliente_id));

CREATE POLICY "operacional_situacao_mudancas_select_same_client"
  ON webproc.operacional_situacao_mudancas
  FOR SELECT
  TO authenticated
  USING (webproc_private.has_active_client_membership(cliente_id));

CREATE POLICY "operacional_intervencoes_select_same_client"
  ON webproc.operacional_intervencoes
  FOR SELECT
  TO authenticated
  USING (webproc_private.has_active_client_membership(cliente_id));
