// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxrnptygbzqzobtdxpwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cm5wdHlnYnpxem9idGR4cHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjMyODQsImV4cCI6MjA3NDczOTI4NH0.NKSBOM7rh4OwABUtzoGEM68Q3DGsCSU4PrKIGoLCUlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});